nacos:
  address: mse-189186c6-p.nacos-ans.mse.aliyuncs.com
  port: 8848
  groupName: TOP
  namespaceId: default
  accessKey: aaa
  secretKey: aaa
  configItems:
    - dataId: common.yaml
      groupName: default
    - dataId: server.yaml
      groupName: default

